# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(865, 671)
        MainWindow.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.647, fx:0.5, fy:0.5, stop:0.104478 rgba(40, 10, 10, 215), stop:0.880597 rgba(0, 0, 0, 255));\n"
"\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame, QLabel, QGroupBox, QStackedWidget {\n"
"    border: 2px solid rgb(90, 1, 1);\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setGeometry(QtCore.QRect(19, 10, 830, 40))
        self.header_frame.setMouseTracking(True)
        self.header_frame.setTabletTracking(True)
        self.header_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.header_frame.setObjectName("header_frame")
        self.titleLabel = QtWidgets.QLabel(self.header_frame)
        self.titleLabel.setGeometry(QtCore.QRect(60, 5, 331, 31))
        self.titleLabel.setMouseTracking(True)
        self.titleLabel.setTabletTracking(True)
        self.titleLabel.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"color: rgb(255, 8, 0);")
        self.titleLabel.setObjectName("titleLabel")
        self.windowButtonsFrame = QtWidgets.QFrame(self.header_frame)
        self.windowButtonsFrame.setGeometry(QtCore.QRect(740, 5, 91, 30))
        self.windowButtonsFrame.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.windowButtonsFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.windowButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.windowButtonsFrame.setObjectName("windowButtonsFrame")
        self.minimizeWindowButton = QtWidgets.QPushButton(self.windowButtonsFrame)
        self.minimizeWindowButton.setGeometry(QtCore.QRect(0, 0, 40, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Specialty")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.minimizeWindowButton.setFont(font)
        self.minimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeWindowButton.setMouseTracking(True)
        self.minimizeWindowButton.setTabletTracking(True)
        self.minimizeWindowButton.setStyleSheet("color: rgb(255, 8, 0);\n"
"font: 12pt \"MS Reference Specialty\";\n"
"")
        self.minimizeWindowButton.setObjectName("minimizeWindowButton")
        self.closeWindowButton = QtWidgets.QPushButton(self.windowButtonsFrame)
        self.closeWindowButton.setGeometry(QtCore.QRect(50, 0, 40, 30))
        self.closeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeWindowButton.setMouseTracking(True)
        self.closeWindowButton.setTabletTracking(True)
        self.closeWindowButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.closeWindowButton.setStyleSheet("color: rgb(255, 8, 0);\n"
"font: 21pt \"Wingdings\";\n"
"border: 1px\n"
"")
        self.closeWindowButton.setCheckable(False)
        self.closeWindowButton.setAutoDefault(False)
        self.closeWindowButton.setObjectName("closeWindowButton")
        self.icon_label = QtWidgets.QLabel(self.header_frame)
        self.icon_label.setGeometry(QtCore.QRect(10, 2, 45, 35))
        self.icon_label.setStyleSheet("border: 0px")
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap("images/iconMin.png"))
        self.icon_label.setObjectName("icon_label")
        self.Figure_2D_box = QtWidgets.QComboBox(self.centralwidget)
        self.Figure_2D_box.setGeometry(QtCore.QRect(19, 60, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.Figure_2D_box.setFont(font)
        self.Figure_2D_box.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.455, x2:1, y2:0, stop:0.323383 rgba(15, 4, 4, 224), stop:0.995025 rgba(255, 255, 255, 217));\n"
"\n"
"color: rgb(218, 218, 218);\n"
"border:2px solid rgb(149, 0, 0);\n"
"border-radius: 10px;\n"
"padding: 1px 15px;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color: rgb(90, 1, 1);\n"
"\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 161, 161, 218));\n"
"color: rgb(218, 218, 218);\n"
"padding: 5px;\n"
"}\n"
"")
        self.Figure_2D_box.setEditable(False)
        self.Figure_2D_box.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.Figure_2D_box.setFrame(True)
        self.Figure_2D_box.setModelColumn(0)
        self.Figure_2D_box.setObjectName("Figure_2D_box")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.Figure_2D_box.addItem("")
        self.groupBox_image = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_image.setGeometry(QtCore.QRect(20, 130, 400, 520))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.groupBox_image.setFont(font)
        self.groupBox_image.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.261, x2:1, y2:0, stop:0 rgba(15, 0, 0, 255), stop:1 rgba(255, 255, 255, 218));\n"
"color: rgb(181, 0, 0);")
        self.groupBox_image.setFlat(False)
        self.groupBox_image.setCheckable(False)
        self.groupBox_image.setObjectName("groupBox_image")
        self.label_image = QtWidgets.QLabel(self.groupBox_image)
        self.label_image.setGeometry(QtCore.QRect(10, 29, 380, 471))
        self.label_image.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.label_image.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("../../../Users/iakuc/Python/PyQt/GUI_calculator/images/figure_paint.gif_3.gif"))
        self.label_image.setObjectName("label_image")
        self.Box_formulas = QtWidgets.QGroupBox(self.centralwidget)
        self.Box_formulas.setGeometry(QtCore.QRect(440, 130, 411, 521))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.Box_formulas.setFont(font)
        self.Box_formulas.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.261, x2:1, y2:0, stop:0 rgba(15, 0, 0, 255), stop:1 rgba(255, 255, 255, 218));\n"
"color: rgb(181, 0, 0);")
        self.Box_formulas.setObjectName("Box_formulas")
        self.stackedWidget_func = QtWidgets.QStackedWidget(self.Box_formulas)
        self.stackedWidget_func.setGeometry(QtCore.QRect(10, 30, 390, 480))
        self.stackedWidget_func.setStyleSheet("QStackedWidget {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(102, 7, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        \n"
"       background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(58, 4, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"        padding-top: 2px;\n"
"        padding-left: 3px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit: focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"\n"
"")
        self.stackedWidget_func.setObjectName("stackedWidget_func")
        self.Input = QtWidgets.QWidget()
        self.Input.setObjectName("Input")
        self.Box_whatsearch = QtWidgets.QComboBox(self.Input)
        self.Box_whatsearch.setGeometry(QtCore.QRect(10, 45, 350, 40))
        self.Box_whatsearch.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Box_whatsearch.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"\n"
"color: rgb(218, 218, 218);\n"
"border:2px solid rgb(149, 0, 0);\n"
"border-radius: 10px;\n"
"padding: 1px 15px;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"\n"
"selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 161, 161, 218));\n"
"color: rgb(218, 218, 218);\n"
"padding: 5px;\n"
"}\n"
"")
        self.Box_whatsearch.setObjectName("Box_whatsearch")
        self.Box_whatsearch.addItem("")
        self.plainTextEdit_figure_input = QtWidgets.QPlainTextEdit(self.Input)
        self.plainTextEdit_figure_input.setGeometry(QtCore.QRect(10, 10, 350, 30))
        self.plainTextEdit_figure_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainTextEdit_figure_input.setStyleSheet("padding: 0px 10px;\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));;\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(102, 7, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"font: 9pt \"Segoe Print\";")
        self.plainTextEdit_figure_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_figure_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_figure_input.setReadOnly(True)
        self.plainTextEdit_figure_input.setObjectName("plainTextEdit_figure_input")
        self.groupBox_pageInput = QtWidgets.QLabel(self.Input)
        self.groupBox_pageInput.setGeometry(QtCore.QRect(5, 90, 361, 330))
        self.groupBox_pageInput.setStyleSheet("border: 0px;\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.647, fx:0.5, fy:0.5, stop:0.104478 rgba(40, 10, 10, 215), stop:0.880597 rgba(32, 0, 0, 229));")
        self.groupBox_pageInput.setText("")
        self.groupBox_pageInput.setObjectName("groupBox_pageInput")
        self.lineEdit_page1_line5 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line5.setEnabled(False)
        self.lineEdit_page1_line5.setGeometry(QtCore.QRect(10, 300, 180, 31))
        self.lineEdit_page1_line5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line5.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line5.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line5.setObjectName("lineEdit_page1_line5")
        self.lineEdit_page1_line3_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line3_input.setGeometry(QtCore.QRect(260, 220, 101, 31))
        self.lineEdit_page1_line3_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line3_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line3_input.setText("")
        self.lineEdit_page1_line3_input.setFrame(True)
        self.lineEdit_page1_line3_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page1_line3_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line3_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line3_input.setObjectName("lineEdit_page1_line3_input")
        self.lineEdit_page1_line4_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line4_input.setGeometry(QtCore.QRect(260, 260, 101, 31))
        self.lineEdit_page1_line4_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line4_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line4_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line4_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line4_input.setObjectName("lineEdit_page1_line4_input")
        self.lineEdit_page1_line7_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line7_input.setGeometry(QtCore.QRect(260, 380, 101, 31))
        self.lineEdit_page1_line7_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line7_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line7_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line7_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line7_input.setObjectName("lineEdit_page1_line7_input")
        self.lineEdit_page1_line1 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line1.setEnabled(False)
        self.lineEdit_page1_line1.setGeometry(QtCore.QRect(10, 140, 180, 31))
        self.lineEdit_page1_line1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_page1_line1.setTabletTracking(False)
        self.lineEdit_page1_line1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_page1_line1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_page1_line1.setStyleSheet("\n"
"")
        self.lineEdit_page1_line1.setText("")
        self.lineEdit_page1_line1.setFrame(True)
        self.lineEdit_page1_line1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_page1_line1.setDragEnabled(False)
        self.lineEdit_page1_line1.setReadOnly(True)
        self.lineEdit_page1_line1.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line1.setClearButtonEnabled(False)
        self.lineEdit_page1_line1.setObjectName("lineEdit_page1_line1")
        self.lineEdit_page1_line2 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line2.setEnabled(False)
        self.lineEdit_page1_line2.setGeometry(QtCore.QRect(10, 180, 180, 31))
        self.lineEdit_page1_line2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_page1_line2.setTabletTracking(False)
        self.lineEdit_page1_line2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_page1_line2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_page1_line2.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line2.setText("")
        self.lineEdit_page1_line2.setFrame(True)
        self.lineEdit_page1_line2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_page1_line2.setDragEnabled(False)
        self.lineEdit_page1_line2.setReadOnly(True)
        self.lineEdit_page1_line2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line2.setClearButtonEnabled(False)
        self.lineEdit_page1_line2.setObjectName("lineEdit_page1_line2")
        self.lineEdit_page1_line6_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line6_input.setGeometry(QtCore.QRect(260, 340, 101, 31))
        self.lineEdit_page1_line6_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line6_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line6_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line6_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line6_input.setObjectName("lineEdit_page1_line6_input")
        self.lineEdit_page1_line5_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line5_input.setGeometry(QtCore.QRect(260, 300, 101, 31))
        self.lineEdit_page1_line5_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line5_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line5_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line5_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line5_input.setObjectName("lineEdit_page1_line5_input")
        self.lineEdit_page1_line6 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line6.setEnabled(False)
        self.lineEdit_page1_line6.setGeometry(QtCore.QRect(10, 340, 180, 31))
        self.lineEdit_page1_line6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line6.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line6.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line6.setObjectName("lineEdit_page1_line6")
        self.text_label_input = QtWidgets.QLabel(self.Input)
        self.text_label_input.setGeometry(QtCore.QRect(10, 95, 350, 30))
        self.text_label_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.text_label_input.setStyleSheet("QLabel {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 255, 255);\n"
"padding: 0px 10px\n"
"\n"
"}")
        self.text_label_input.setObjectName("text_label_input")
        self.lineEdit_page1_line4 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line4.setEnabled(False)
        self.lineEdit_page1_line4.setGeometry(QtCore.QRect(10, 260, 180, 31))
        self.lineEdit_page1_line4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line4.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line4.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line4.setObjectName("lineEdit_page1_line4")
        self.lineEdit_page1_line2_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line2_input.setGeometry(QtCore.QRect(260, 180, 101, 31))
        self.lineEdit_page1_line2_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line2_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line2_input.setText("")
        self.lineEdit_page1_line2_input.setFrame(True)
        self.lineEdit_page1_line2_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page1_line2_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line2_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line2_input.setObjectName("lineEdit_page1_line2_input")
        self.lineEdit_page1_line3 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line3.setEnabled(False)
        self.lineEdit_page1_line3.setGeometry(QtCore.QRect(10, 220, 180, 31))
        self.lineEdit_page1_line3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_page1_line3.setTabletTracking(False)
        self.lineEdit_page1_line3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_page1_line3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_page1_line3.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line3.setText("")
        self.lineEdit_page1_line3.setFrame(True)
        self.lineEdit_page1_line3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_page1_line3.setDragEnabled(False)
        self.lineEdit_page1_line3.setReadOnly(True)
        self.lineEdit_page1_line3.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line3.setClearButtonEnabled(False)
        self.lineEdit_page1_line3.setObjectName("lineEdit_page1_line3")
        self.lineEdit_page1_line7 = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line7.setEnabled(False)
        self.lineEdit_page1_line7.setGeometry(QtCore.QRect(10, 380, 180, 31))
        self.lineEdit_page1_line7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line7.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page1_line7.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line7.setObjectName("lineEdit_page1_line7")
        self.lineEdit_page1_line1_input = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_page1_line1_input.setGeometry(QtCore.QRect(260, 140, 101, 31))
        self.lineEdit_page1_line1_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_page1_line1_input.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"}\n"
"\n"
"")
        self.lineEdit_page1_line1_input.setText("")
        self.lineEdit_page1_line1_input.setFrame(True)
        self.lineEdit_page1_line1_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page1_line1_input.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page1_line1_input.setClearButtonEnabled(True)
        self.lineEdit_page1_line1_input.setObjectName("lineEdit_page1_line1_input")
        self.Calculate = QtWidgets.QPushButton(self.Input)
        self.Calculate.setGeometry(QtCore.QRect(10, 425, 361, 41))
        self.Calculate.setStyleSheet("\n"
"\n"
"")
        self.Calculate.setObjectName("Calculate")
        self.stackedWidget_func.addWidget(self.Input)
        self.Output = QtWidgets.QWidget()
        self.Output.setObjectName("Output")
        self.plainTextEdit_figure_output = QtWidgets.QPlainTextEdit(self.Output)
        self.plainTextEdit_figure_output.setGeometry(QtCore.QRect(10, 20, 350, 30))
        self.plainTextEdit_figure_output.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainTextEdit_figure_output.setStyleSheet("padding: 0px 10px;\n"
"background-color:qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(102, 7, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"\n"
"")
        self.plainTextEdit_figure_output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_figure_output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_figure_output.setReadOnly(True)
        self.plainTextEdit_figure_output.setObjectName("plainTextEdit_figure_output")
        self.text_label_result = QtWidgets.QLabel(self.Output)
        self.text_label_result.setGeometry(QtCore.QRect(10, 60, 350, 30))
        self.text_label_result.setStyleSheet("QLabel {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 255, 255);\n"
"padding: 0px 10px\n"
"\n"
"}")
        self.text_label_result.setObjectName("text_label_result")
        self.groupBox_pageOutput = QtWidgets.QGroupBox(self.Output)
        self.groupBox_pageOutput.setGeometry(QtCore.QRect(0, 120, 381, 351))
        self.groupBox_pageOutput.setStyleSheet("border: 0px")
        self.groupBox_pageOutput.setTitle("")
        self.groupBox_pageOutput.setObjectName("groupBox_pageOutput")
        self.paint_figure = QtWidgets.QPushButton(self.groupBox_pageOutput)
        self.paint_figure.setGeometry(QtCore.QRect(10, 300, 360, 40))
        self.paint_figure.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paint_figure.setAcceptDrops(False)
        self.paint_figure.setAutoFillBackground(False)
        self.paint_figure.setStyleSheet("")
        self.paint_figure.setAutoDefault(False)
        self.paint_figure.setFlat(True)
        self.paint_figure.setObjectName("paint_figure")
        self.lineEdit_page2_line1 = QtWidgets.QLineEdit(self.groupBox_pageOutput)
        self.lineEdit_page2_line1.setEnabled(False)
        self.lineEdit_page2_line1.setGeometry(QtCore.QRect(10, 10, 180, 31))
        self.lineEdit_page2_line1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_page2_line1.setTabletTracking(False)
        self.lineEdit_page2_line1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_page2_line1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_page2_line1.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page2_line1.setFrame(True)
        self.lineEdit_page2_line1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_page2_line1.setDragEnabled(False)
        self.lineEdit_page2_line1.setReadOnly(True)
        self.lineEdit_page2_line1.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page2_line1.setClearButtonEnabled(False)
        self.lineEdit_page2_line1.setObjectName("lineEdit_page2_line1")
        self.lineEdit_page2_line2 = QtWidgets.QLineEdit(self.groupBox_pageOutput)
        self.lineEdit_page2_line2.setEnabled(False)
        self.lineEdit_page2_line2.setGeometry(QtCore.QRect(10, 50, 180, 31))
        self.lineEdit_page2_line2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_page2_line2.setTabletTracking(False)
        self.lineEdit_page2_line2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_page2_line2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_page2_line2.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page2_line2.setFrame(True)
        self.lineEdit_page2_line2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_page2_line2.setDragEnabled(False)
        self.lineEdit_page2_line2.setReadOnly(True)
        self.lineEdit_page2_line2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page2_line2.setClearButtonEnabled(False)
        self.lineEdit_page2_line2.setObjectName("lineEdit_page2_line2")
        self.lineEdit_page2_line2_out = QtWidgets.QLineEdit(self.groupBox_pageOutput)
        self.lineEdit_page2_line2_out.setEnabled(False)
        self.lineEdit_page2_line2_out.setGeometry(QtCore.QRect(260, 50, 101, 31))
        self.lineEdit_page2_line2_out.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page2_line2_out.setFrame(True)
        self.lineEdit_page2_line2_out.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page2_line2_out.setReadOnly(True)
        self.lineEdit_page2_line2_out.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page2_line2_out.setClearButtonEnabled(False)
        self.lineEdit_page2_line2_out.setObjectName("lineEdit_page2_line2_out")
        self.lineEdit_page2_line1_out = QtWidgets.QLineEdit(self.groupBox_pageOutput)
        self.lineEdit_page2_line1_out.setEnabled(False)
        self.lineEdit_page2_line1_out.setGeometry(QtCore.QRect(260, 10, 101, 31))
        self.lineEdit_page2_line1_out.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(209, 0, 0);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_page2_line1_out.setFrame(True)
        self.lineEdit_page2_line1_out.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page2_line1_out.setReadOnly(True)
        self.lineEdit_page2_line1_out.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_page2_line1_out.setClearButtonEnabled(False)
        self.lineEdit_page2_line1_out.setObjectName("lineEdit_page2_line1_out")
        self.plainTextEdit_page2_about_result = QtWidgets.QPlainTextEdit(self.groupBox_pageOutput)
        self.plainTextEdit_page2_about_result.setGeometry(QtCore.QRect(10, 110, 360, 170))
        self.plainTextEdit_page2_about_result.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainTextEdit_page2_about_result.setStyleSheet("padding: 0px 10px;\n"
"background-color: rgba(127, 0, 0, 50);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(90, 1, 1);\n"
"selection-background-color: rgba(129, 0, 0, 50);\n"
"")
        self.plainTextEdit_page2_about_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_page2_about_result.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_page2_about_result.setReadOnly(True)
        self.plainTextEdit_page2_about_result.setObjectName("plainTextEdit_page2_about_result")
        self.stackedWidget_func.addWidget(self.Output)
        self.Description = QtWidgets.QWidget()
        self.Description.setStyleSheet("QWidget {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.Description.setObjectName("Description")
        self.text_descriptions = QtWidgets.QTextBrowser(self.Description)
        self.text_descriptions.setGeometry(QtCore.QRect(10, 20, 361, 441))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_descriptions.setFont(font)
        self.text_descriptions.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.text_descriptions.setStyleSheet("QTextBrowser {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(127, 0, 0, 50);\n"
"font: 12pt \"Segoe Print\";\n"
"\n"
"}\n"
"")
        self.text_descriptions.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_descriptions.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.text_descriptions.setObjectName("text_descriptions")
        self.stackedWidget_func.addWidget(self.Description)
        self.switch_left = QtWidgets.QToolButton(self.Box_formulas)
        self.switch_left.setGeometry(QtCore.QRect(326, 5, 35, 22))
        self.switch_left.setStyleSheet("QToolButton {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(12, 0, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 8, 0);\n"
"font: 12pt \"Symbol\";\n"
"}")
        self.switch_left.setObjectName("switch_left")
        self.switch_right = QtWidgets.QToolButton(self.Box_formulas)
        self.switch_right.setGeometry(QtCore.QRect(357, 5, 35, 22))
        self.switch_right.setStyleSheet("QToolButton {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(12, 0, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 8, 0);\n"
"font: 12pt \"Symbol\";\n"
"}")
        self.switch_right.setObjectName("switch_right")
        self.Figure_3D_box = QtWidgets.QComboBox(self.centralwidget)
        self.Figure_3D_box.setGeometry(QtCore.QRect(450, 60, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.Figure_3D_box.setFont(font)
        self.Figure_3D_box.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.455, x2:1, y2:0, stop:0.323383 rgba(15, 4, 4, 224), stop:0.995025 rgba(255, 255, 255, 217));\n"
"\n"
"color: rgb(218, 218, 218);\n"
"border:2px solid rgb(149, 0, 0);\n"
"border-radius: 10px;\n"
"padding: 1px 15px;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color: rgb(90, 1, 1);\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 161, 161, 218));\n"
"color: rgb(218, 218, 218);\n"
"padding: 5px;\n"
"}\n"
"")
        self.Figure_3D_box.setEditable(False)
        self.Figure_3D_box.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.Figure_3D_box.setFrame(True)
        self.Figure_3D_box.setModelColumn(0)
        self.Figure_3D_box.setObjectName("Figure_3D_box")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        self.Figure_3D_box.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Figure_2D_box.setCurrentIndex(0)
        self.stackedWidget_func.setCurrentIndex(0)
        self.Figure_3D_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Графический калькулятор"))
        self.minimizeWindowButton.setText(_translate("MainWindow", "8"))
        self.closeWindowButton.setText(_translate("MainWindow", "û"))
        self.Figure_2D_box.setItemText(0, _translate("MainWindow", "Плоские фигуры"))
        self.Figure_2D_box.setItemText(1, _translate("MainWindow", "Прямоугольник"))
        self.Figure_2D_box.setItemText(2, _translate("MainWindow", "Параллелограмм"))
        self.Figure_2D_box.setItemText(3, _translate("MainWindow", "Квадрат"))
        self.Figure_2D_box.setItemText(4, _translate("MainWindow", "Ромб"))
        self.Figure_2D_box.setItemText(5, _translate("MainWindow", "Трапеция равнобедренная"))
        self.Figure_2D_box.setItemText(6, _translate("MainWindow", "Трапеция прямоугольная"))
        self.Figure_2D_box.setItemText(7, _translate("MainWindow", "Треугольник"))
        self.Figure_2D_box.setItemText(8, _translate("MainWindow", "Шестиугольник"))
        self.Figure_2D_box.setItemText(9, _translate("MainWindow", "Окружность"))
        self.groupBox_image.setTitle(_translate("MainWindow", "Объект"))
        self.Box_formulas.setTitle(_translate("MainWindow", "Данные/Результат/Свойства"))
        self.Box_whatsearch.setCurrentText(_translate("MainWindow", "Что нужно найти?"))
        self.Box_whatsearch.setItemText(0, _translate("MainWindow", "Что нужно найти?"))
        self.plainTextEdit_figure_input.setPlainText(_translate("MainWindow", "Выберите фигуру!"))
        self.text_label_input.setText(_translate("MainWindow", "Выберите параметр для поиска"))
        self.Calculate.setText(_translate("MainWindow", "Посчитать"))
        self.plainTextEdit_figure_output.setPlainText(_translate("MainWindow", "Выберите фигуру!"))
        self.text_label_result.setText(_translate("MainWindow", "Результат"))
        self.paint_figure.setText(_translate("MainWindow", "Нарисовать фигуру"))
        self.lineEdit_page2_line1.setText(_translate("MainWindow", "dsfsgfdg"))
        self.lineEdit_page2_line2.setText(_translate("MainWindow", "gfswfgefq"))
        self.lineEdit_page2_line2_out.setText(_translate("MainWindow", "414113"))
        self.lineEdit_page2_line1_out.setText(_translate("MainWindow", "55413"))
        self.plainTextEdit_page2_about_result.setPlainText(_translate("MainWindow", "54154154655\n"
"kljmkljmkjm;\n"
"m;m;"))
        self.text_descriptions.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Прямоугольник - это 4-х угольник у которого две противоположные стороны равны и все углы равны и прямые (90 градусов). <br />________________________________<br />1. AB =CD, BC=AD<br />2. AB || CD, BC || AD<br />3. AB ┴ BC, BC ┴ CD, CD ┴ AD, AD ┴ AB<br />4. AC = BD<br />5. 2d2 = 2a2 + 2b2<br />6. AO = BO = CO = DO = d/2<br />7. Диагональ прямоугольника является диаметром описанной окружности</span></p></body></html>"))
        self.switch_left.setText(_translate("MainWindow", "¬"))
        self.switch_right.setText(_translate("MainWindow", "®"))
        self.Figure_3D_box.setItemText(0, _translate("MainWindow", "Объемные фигуры"))
        self.Figure_3D_box.setItemText(1, _translate("MainWindow", "Призма"))
        self.Figure_3D_box.setItemText(2, _translate("MainWindow", "Параллелепипед"))
        self.Figure_3D_box.setItemText(3, _translate("MainWindow", "Куб"))
        self.Figure_3D_box.setItemText(4, _translate("MainWindow", "Пирамида"))
        self.Figure_3D_box.setItemText(5, _translate("MainWindow", "Цилиндр круговой"))
        self.Figure_3D_box.setItemText(6, _translate("MainWindow", "Конус круговой"))
        self.Figure_3D_box.setItemText(7, _translate("MainWindow", "Шар, сфера"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
