# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(857, 602)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.647, fx:0.5, fy:0.5, stop:0.104478 rgba(40, 10, 10, 215), stop:0.880597 rgba(0, 0, 0, 255));\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame, QLabel, QGroupBox {\n"
"    border: 2px solid rgb(90, 1, 1);\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setGeometry(QtCore.QRect(10, 10, 831, 40))
        self.header_frame.setMouseTracking(True)
        self.header_frame.setTabletTracking(True)
        self.header_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.header_frame.setObjectName("header_frame")
        self.titleLabel = QtWidgets.QLabel(self.header_frame)
        self.titleLabel.setGeometry(QtCore.QRect(10, 5, 331, 31))
        self.titleLabel.setMouseTracking(True)
        self.titleLabel.setTabletTracking(True)
        self.titleLabel.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"Segoe Print\";\n"
"color: rgb(255, 8, 0);")
        self.titleLabel.setObjectName("titleLabel")
        self.windowButtonsFrame = QtWidgets.QFrame(self.header_frame)
        self.windowButtonsFrame.setGeometry(QtCore.QRect(740, 5, 91, 30))
        self.windowButtonsFrame.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.windowButtonsFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.windowButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.windowButtonsFrame.setObjectName("windowButtonsFrame")
        self.minimizeWindowButton = QtWidgets.QPushButton(self.windowButtonsFrame)
        self.minimizeWindowButton.setGeometry(QtCore.QRect(0, 0, 40, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Specialty")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.minimizeWindowButton.setFont(font)
        self.minimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeWindowButton.setMouseTracking(True)
        self.minimizeWindowButton.setTabletTracking(True)
        self.minimizeWindowButton.setStyleSheet("color: rgb(255, 8, 0);\n"
"font: 12pt \"MS Reference Specialty\";\n"
"")
        self.minimizeWindowButton.setObjectName("minimizeWindowButton")
        self.closeWindowButton = QtWidgets.QPushButton(self.windowButtonsFrame)
        self.closeWindowButton.setGeometry(QtCore.QRect(50, 0, 40, 30))
        self.closeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeWindowButton.setMouseTracking(True)
        self.closeWindowButton.setTabletTracking(True)
        self.closeWindowButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.closeWindowButton.setStyleSheet("color: rgb(255, 8, 0);\n"
"font: 21pt \"Wingdings\";\n"
"border: 1px\n"
"")
        self.closeWindowButton.setCheckable(False)
        self.closeWindowButton.setAutoDefault(False)
        self.closeWindowButton.setObjectName("closeWindowButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(19, 60, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.455, x2:1, y2:0, stop:0.323383 rgba(15, 4, 4, 224), stop:0.995025 rgba(255, 255, 255, 217));\n"
"\n"
"color: rgb(218, 218, 218);\n"
"border:2px solid rgb(149, 0, 0);\n"
"border-radius: 10px;\n"
"padding: 1px 15px;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color: rgb(90, 1, 1);\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
";\n"
"    selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 161, 161, 218));\n"
"color: rgb(218, 218, 218);\n"
"padding: 5px;\n"
"}\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setFrame(True)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 60, 400, 51))
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.455, x2:1, y2:0, stop:0.323383 rgba(15, 4, 4, 224), stop:0.995025 rgba(255, 255, 255, 217));\n"
"\n"
"color: rgb(218, 218, 218);\n"
"border:2px solid rgb(149, 0, 0);\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color: rgb(90, 1, 1);\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"selection-background-color:  qlineargradient(spread:reflect, x1:1, y1:0.455, x2:1, y2:0, stop:0.323383 rgba(15, 4, 4, 224), stop:0.995025 rgba(255, 255, 255, 217));\n"
"color: rgb(218, 218, 218);\n"
"padding: 5px;\n"
"}\n"
"")
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setModelColumn(1)
        self.comboBox_2.setObjectName("comboBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 401, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.261, x2:1, y2:0, stop:0 rgba(15, 0, 0, 255), stop:1 rgba(255, 255, 255, 218));\n"
"color: rgb(0, 0, 0);")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 380, 420))
        self.label_5.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../Users/iakuc/Python/PyQt/GUI_calculator/images/figure_paint.gif_3.gif"))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 130, 400, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.261, x2:1, y2:0, stop:0 rgba(15, 0, 0, 255), stop:1 rgba(255, 255, 255, 218));\n"
"color: rgb(0, 0, 0);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_5.setEnabled(False)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(10, 50, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 1px 15px\n"
"\n"
"\n"
"")
        self.plainTextEdit_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_49.setEnabled(False)
        self.lineEdit_49.setGeometry(QtCore.QRect(10, 110, 180, 31))
        self.lineEdit_49.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_49.setTabletTracking(False)
        self.lineEdit_49.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_49.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_49.setFrame(True)
        self.lineEdit_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_49.setDragEnabled(False)
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_49.setClearButtonEnabled(False)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_50.setEnabled(False)
        self.lineEdit_50.setGeometry(QtCore.QRect(10, 150, 180, 31))
        self.lineEdit_50.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_50.setTabletTracking(False)
        self.lineEdit_50.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_50.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_50.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_50.setFrame(True)
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_50.setDragEnabled(False)
        self.lineEdit_50.setReadOnly(True)
        self.lineEdit_50.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_50.setClearButtonEnabled(False)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_51.setEnabled(False)
        self.lineEdit_51.setGeometry(QtCore.QRect(10, 190, 180, 31))
        self.lineEdit_51.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEdit_51.setTabletTracking(False)
        self.lineEdit_51.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_51.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_51.setFrame(True)
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_51.setDragEnabled(False)
        self.lineEdit_51.setReadOnly(True)
        self.lineEdit_51.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_51.setClearButtonEnabled(False)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_52.setEnabled(False)
        self.lineEdit_52.setGeometry(QtCore.QRect(10, 230, 180, 31))
        self.lineEdit_52.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_52.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_53.setEnabled(False)
        self.lineEdit_53.setGeometry(QtCore.QRect(10, 270, 180, 31))
        self.lineEdit_53.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_53.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_54.setEnabled(False)
        self.lineEdit_54.setGeometry(QtCore.QRect(10, 310, 180, 31))
        self.lineEdit_54.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"padding: 5px\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_54.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_55.setGeometry(QtCore.QRect(260, 110, 101, 31))
        self.lineEdit_55.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_55.setFrame(True)
        self.lineEdit_55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_55.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_55.setClearButtonEnabled(True)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_56.setGeometry(QtCore.QRect(260, 150, 101, 31))
        self.lineEdit_56.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_56.setFrame(True)
        self.lineEdit_56.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_56.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_56.setClearButtonEnabled(True)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_57.setGeometry(QtCore.QRect(260, 190, 101, 31))
        self.lineEdit_57.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_57.setFrame(True)
        self.lineEdit_57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_57.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_57.setClearButtonEnabled(True)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_58.setGeometry(QtCore.QRect(260, 230, 101, 31))
        self.lineEdit_58.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_58.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_59.setGeometry(QtCore.QRect(260, 270, 101, 31))
        self.lineEdit_59.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_59.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_60.setGeometry(QtCore.QRect(260, 310, 101, 31))
        self.lineEdit_60.setStyleSheet("QLineEdit {\n"
"background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(245, 229, 228);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(56, 56, 56);\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"}\n"
"")
        self.lineEdit_60.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_60.setObjectName("lineEdit_60")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Графический калькулятор"))
        self.minimizeWindowButton.setText(_translate("MainWindow", "8"))
        self.closeWindowButton.setText(_translate("MainWindow", "û"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Плоские фигуры"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Квадрат"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Круг"))
        self.comboBox.setItemText(3, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(5, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(6, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(7, _translate("MainWindow", "New Item"))
        self.groupBox.setTitle(_translate("MainWindow", "Объект"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Данные/Результат/Свойства"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "ьпдлоьлкпьолкоьпь"))
        self.lineEdit_49.setText(_translate("MainWindow", "dsfsgfdg"))
        self.lineEdit_50.setText(_translate("MainWindow", "gfswfgefq"))
        self.lineEdit_51.setText(_translate("MainWindow", "fdsf"))
        self.lineEdit_55.setText(_translate("MainWindow", "55413"))
        self.lineEdit_56.setText(_translate("MainWindow", "414113"))
        self.lineEdit_57.setText(_translate("MainWindow", "55145"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
