# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ErrorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path


class Ui_ErrorWindow(object):
    def __init__(self, text="", details=""):
        self.text = text
        self.details = details

    def setupUi(self, ErrorWindow):
        ErrorWindow.setObjectName("ErrorWindow")
        ErrorWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        ErrorWindow.resize(715, 224)
        ErrorWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        ErrorWindow.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.647, fx:0.5, fy:0.5, stop:0.104478 rgba(40, 10, 10, 215), stop:0.880597 rgba(0, 0, 0, 255));\n"
"\n"
"")
        font_id = QtGui.QFontDatabase.addApplicationFont(f"{Path.cwd() / 'fonts' / 'Laptev_Brush.otf'}")
        if font_id == -1:
                raise FileNotFoundError("Шрифт 'Laptev_Brush.otf' не установлен")

        self.fontName = QtGui.QFontDatabase.applicationFontFamilies(font_id)[0]
        self.fontSegoe = QtGui.QFont("Segoe Print", 9)
        self.font = QtGui.QFont(self.fontName, 17)

        ErrorWindow.setFont(self.font)

        ErrorWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(ErrorWindow)
        self.centralwidget.setStyleSheet("QFrame,  QGroupBox, QStackedWidget {\n"
"    border: 2px solid rgb(90, 1, 1);\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"    \n"
"}\n"
"QPushButton {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0.174129 rgba(15, 0, 0, 255), stop:0.890547 rgba(161, 100, 100, 218));\n"
"color: rgb(255, 255, 255);\n"
f"font: bold 12pt {self.fontName};\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(102, 7, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(58, 4, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"padding-top: 2px;\n"
"padding-left: 3px;\n"
"}\n"
"QPlainTextEdit {\n"
"padding: 5px 20px;\n"
"color: rgb(255, 8, 0);\n"
"font: 10pt 'Segoe Print';\n"
"selection-color: white;\n"
"selection-background-color: qlineargradient(spread:reflect, x1:1, y1:0.522, x2:1, y2:0, stop:0 rgba(102, 7, 0, 240), stop:0.80597 rgba(161, 100, 100, 218));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setGeometry(QtCore.QRect(19, 10, 680, 40))
        self.header_frame.setMouseTracking(True)
        self.header_frame.setTabletTracking(True)
        self.header_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.header_frame.setObjectName("header_frame")
        self.titleLabel = QtWidgets.QLabel(self.header_frame)
        self.titleLabel.setGeometry(QtCore.QRect(60, 5, 331, 31))
        self.titleLabel.setMouseTracking(True)
        self.titleLabel.setTabletTracking(True)
        self.titleLabel.setStyleSheet("border: 0px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
f"font: bold 14pt {self.fontName};\n"
"color: rgb(255, 8, 0);")
        self.titleLabel.setObjectName("titleLabel")
        self.windowButtonsFrame = QtWidgets.QFrame(self.header_frame)
        self.windowButtonsFrame.setGeometry(QtCore.QRect(580, 5, 91, 30))
        self.windowButtonsFrame.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.windowButtonsFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.windowButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.windowButtonsFrame.setObjectName("windowButtonsFrame")

        self.questionWindowButton = QtWidgets.QPushButton(self.windowButtonsFrame)
        self.questionWindowButton.setGeometry(QtCore.QRect(0, 0, 40, 30))
        self.questionWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.questionWindowButton.setMouseTracking(True)
        self.questionWindowButton.setTabletTracking(True)
        self.questionWindowButton.setStyleSheet("color: rgb(255, 8, 0);\n"
"font: bold 12pt \"Segoe Print\";\n"
"")
        self.questionWindowButton.setObjectName("questionWindowButton")

        self.closeWindowButton = QtWidgets.QPushButton(self.windowButtonsFrame)
        self.closeWindowButton.setGeometry(QtCore.QRect(50, 0, 40, 30))
        self.closeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeWindowButton.setMouseTracking(True)
        self.closeWindowButton.setTabletTracking(True)
        self.closeWindowButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.closeWindowButton.setStyleSheet("color: rgb(255, 8, 0);\n"
"font: 21pt \"Wingdings\";\n"
"border: 1px\n"
"")
        self.closeWindowButton.setCheckable(False)
        self.closeWindowButton.setAutoDefault(False)
        self.closeWindowButton.setObjectName("closeWindowButton")

        self.icon_label = QtWidgets.QLabel(self.header_frame)
        self.icon_label.setGeometry(QtCore.QRect(10, 2, 45, 35))
        self.icon_label.setStyleSheet("border: 0px")
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap("images/iconMin.png"))
        self.icon_label.setObjectName("icon_label")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 110, 110))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/error_ops2.png"))
        self.label.setObjectName("label")

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(140, 60, 550, 110))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.plainTextEdit_details = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_details.setGeometry(QtCore.QRect(20, 230, 671, 141))
        self.plainTextEdit_details.setReadOnly(True)
        self.plainTextEdit_details.setObjectName("plainTextEdit_details")

        self.btn_details = QtWidgets.QPushButton(self.centralwidget)
        self.btn_details.setGeometry(QtCore.QRect(550, 180, 130, 30))
        self.btn_details.setObjectName("btn_details")

        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(410, 180, 130, 30))
        self.btn_ok.setObjectName("btn_ok")

        ErrorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ErrorWindow)
        QtCore.QMetaObject.connectSlotsByName(ErrorWindow)

        self.add_functions()

    def retranslateUi(self, ErrorWindow):
        _translate = QtCore.QCoreApplication.translate
        ErrorWindow.setWindowTitle(_translate("ErrorWindow", "ErrorWindow"))
        self.titleLabel.setText(_translate("ErrorWindow", "Ошибка"))
        self.questionWindowButton.setText(_translate("ErrorWindow", "?"))
        self.closeWindowButton.setText(_translate("ErrorWindow", "û"))
        self.btn_details.setText(_translate("ErrorWindow", "Детали"))
        self.btn_ok.setText(_translate("ErrorWindow", "ОК"))
        self.plainTextEdit.setPlainText(_translate("ErrorWindow", f"{self.text}"))
        self.plainTextEdit_details.setPlainText(_translate("ErrorWindow", f"{self.details}"))


    def add_functions(self):
            pass
