# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ErrorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from pathlib import Path

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer


class Ui_ErrorWindow(object):
    def __init__(self, text="", details=""):
        self.text = text
        self.details = details
    
    def setupUi(self, ErrorWindow):
        ErrorWindow.setObjectName("ErrorWindow")
        ErrorWindow.resize(560, 175)
        ErrorWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ErrorWindow.sizePolicy().hasHeightForWidth())
        ErrorWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(16)
        font.setItalic(True)
        ErrorWindow.setFont(font)
        ErrorWindow.setStyleSheet("background-color: rgb(58, 58, 58);\n"
"color: rgb(57, 255, 87);\n"
"selection-color: rgb(57, 255, 87);\n"
"selection-background-color: rgb(58, 58, 58);")
        ErrorWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        ErrorWindow.setTabShape(QtWidgets.QTabWidget.Triangular)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.centralwidget = QtWidgets.QWidget(ErrorWindow)
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        
        self.sound = QMediaPlayer(self.centralwidget)
        self.sound.setVolume(100)
        path_sound = Path.cwd()/"sound"/"error.mp3"   # os.path.join(os.getcwd(), r'sound\error.mp3')
        file = QUrl.fromLocalFile(f"{path_sound}")
        sound = QMediaContent(file)
        self.sound.setMedia(sound)
        self.sound.play()
        
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 110, 110))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/error_ops2.png"))
        self.label.setObjectName("label")
        
        self.btn_details = QtWidgets.QPushButton(self.centralwidget)
        self.btn_details.setGeometry(QtCore.QRect(430, 130, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_details.setFont(font)
        self.btn_details.setObjectName("btn_details")
        
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(300, 130, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ok.setFont(font)
        self.btn_ok.setObjectName("btn_ok")
        
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 10, 410, 110))
        self.plainTextEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit.setObjectName("plainTextEdit")
        ErrorWindow.setCentralWidget(self.centralwidget)

        self.plainTextEdit_details = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_details.setGeometry(QtCore.QRect(10, 140, 530, 130))
        self.plainTextEdit_details.setReadOnly(True)
        #self.plainTextEdit_details.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.plainTextEdit_details.setFont(font)
        self.plainTextEdit_details.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit_details.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit_details.setHidden(True)
        self.plainTextEdit_details.setObjectName("plainTextEdit_details")
        
        self.retranslateUi(ErrorWindow)
        QtCore.QMetaObject.connectSlotsByName(ErrorWindow)

    def retranslateUi(self, ErrorWindow):
        _translate = QtCore.QCoreApplication.translate
        ErrorWindow.setWindowTitle(_translate("ErrorWindow", "Ошибка"))
        self.btn_details.setText(_translate("ErrorWindow", "Детали"))
        self.btn_ok.setText(_translate("ErrorWindow", "OK"))
        self.plainTextEdit.setPlainText(_translate("ErrorWindow", f"{self.text}"))
        self.plainTextEdit_details.setPlainText(_translate("ErrorWindow", f"{self.details}"))





