# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MatplotlibWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QLocale
from PyQt5.QtGui import QDoubleValidator


class Ui_MatplotlibWindow(object):
    def __init__(self, figure=""):
        self.figure = figure


    def setupUi(self, MatplotlibWindow):
        # ToDo поискать решение получше для передачи фигуры

        QLocale.setDefault(QLocale(QLocale(QLocale.English, QLocale.UnitedStates)))
        MatplotlibWindow.setObjectName("MatplotlibWindow")
        MatplotlibWindow.resize(740, 620)
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        MatplotlibWindow.setFont(font)
        MatplotlibWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MatplotlibWindow.setStyleSheet("background-color: rgb(69, 69, 69);\n"
                                       "selection-color: rgb(57, 255, 87);\n"
                                       "selection-background-color: rgb(90, 90, 90);")
        '''self.centralwidget = QtWidgets.QWidget(MatplotlibWindow)
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(11)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(69, 69, 69);")
        self.centralwidget.setObjectName("centralwidget")'''
        self.label_matplot_image = QtWidgets.QLabel(MatplotlibWindow)
        self.label_matplot_image.setGeometry(QtCore.QRect(10, 10, 720, 480))
        self.label_matplot_image.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                               "color: rgb(57, 255, 87);\n"
                                               "selection-color: rgb(57, 255, 87);\n"
                                               "selection-background-color: rgb(58, 58, 58);")
        self.label_matplot_image.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_matplot_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_matplot_image.setText("")
        self.label_matplot_image.setObjectName("label_matplot_image")

        self.pushButton_go = QtWidgets.QPushButton(MatplotlibWindow)
        self.pushButton_go.setGeometry(QtCore.QRect(530, 500, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.pushButton_go.setFont(font)
        self.pushButton_go.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                         "color: rgb(57, 255, 87);\n"
                                         "selection-color: rgb(57, 255, 87);\n"
                                         "selection-background-color: rgb(58, 58, 58);")
        self.pushButton_go.setObjectName("pushButton_go")

        self.pushButton_save = QtWidgets.QPushButton(MatplotlibWindow)
        self.pushButton_save.setGeometry(QtCore.QRect(530, 540, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                           "color: rgb(57, 255, 87);\n"
                                           "selection-color: rgb(57, 255, 87);\n"
                                           "selection-background-color: rgb(58, 58, 58);")
        self.pushButton_save.setObjectName("pushButton_save")

        self.label_3 = QtWidgets.QLabel(MatplotlibWindow)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(20, 580, 170, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                   "color: rgb(57, 255, 87);\n"
                                   "selection-color: rgb(57, 255, 87);\n"
                                   "selection-background-color: rgb(58, 58, 58);")
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(MatplotlibWindow)
        self.label_1.setEnabled(False)
        self.label_1.setGeometry(QtCore.QRect(20, 500, 170, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                   "color: rgb(57, 255, 87);\n"
                                   "selection-color: rgb(57, 255, 87);\n"
                                   "selection-background-color: rgb(58, 58, 58);")
        self.label_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(MatplotlibWindow)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(20, 540, 170, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                   "color: rgb(57, 255, 87);\n"
                                   "selection-color: rgb(57, 255, 87);\n"
                                   "selection-background-color: rgb(58, 58, 58);")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        self.matplot_widget = QtWidgets.QWidget(MatplotlibWindow)
        self.matplot_widget.setGeometry(QtCore.QRect(30, 30, 680, 440))
        self.matplot_widget.setStyleSheet("\n"
                                          "background-color: rgb(213, 213, 213);")
        self.matplot_widget.setObjectName("matplot_widget")

        self.label_widget = QtWidgets.QLabel(self.matplot_widget)
        self.label_widget.setGeometry(QtCore.QRect(10, 10, 450, 410))
        self.label_widget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_widget.setText("")
        self.label_widget.setObjectName("label_widget")

        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(self.matplot_widget)
        self.plainTextEdit_result.setGeometry(QtCore.QRect(480, 10, 180, 410))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.plainTextEdit_result.setFont(font)
        self.plainTextEdit_result.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit_result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit_result.setStyleSheet("color: rgb(29, 29, 29);")
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.plainTextEdit_result.setReadOnly(True)

        self.widget_plot = QtWidgets.QWidget(self.matplot_widget)
        self.widget_plot.setGeometry(QtCore.QRect(20, 20, 430, 390))
        self.widget_plot.setObjectName("widget_plot")

        self.label_2_input = QtWidgets.QLineEdit(MatplotlibWindow)
        self.label_2_input.setEnabled(True)
        self.label_2_input.setGeometry(QtCore.QRect(210, 540, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_2_input.setFont(font)
        self.label_2_input.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                         "color: rgb(57, 255, 87);\n"
                                         "selection-color: rgb(57, 255, 87);\n"
                                         "selection-background-color: rgb(58, 58, 58);")
        self.label_2_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2_input.setTabletTracking(False)
        self.label_2_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_2_input.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_2_input.setInputMask("")
        self.label_2_input.setText("")
        self.label_2_input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.label_2_input.setClearButtonEnabled(False)
        self.label_2_input.setFrame(False)
        self.label_2_input.setValidator(QDoubleValidator(0.999, 999.99, 2))
        self.label_2_input.setMaxLength(5)
        self.label_2_input.setObjectName("label_2_input")

        self.label_1_input = QtWidgets.QLineEdit(MatplotlibWindow)
        self.label_1_input.setEnabled(True)
        self.label_1_input.setGeometry(QtCore.QRect(210, 500, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_1_input.setFont(font)
        self.label_1_input.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                         "color: rgb(57, 255, 87);\n"
                                         "selection-color: rgb(57, 255, 87);\n"
                                         "selection-background-color: rgb(58, 58, 58);")
        self.label_1_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_1_input.setTabletTracking(False)
        self.label_1_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_1_input.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_1_input.setInputMask("")
        self.label_1_input.setText("")
        self.label_1_input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.label_1_input.setClearButtonEnabled(False)
        self.label_1_input.setFrame(False)
        self.label_1_input.setValidator(QDoubleValidator(0.999, 999.99, 2))
        self.label_1_input.setMaxLength(5)

        self.label_1_input.setObjectName("label_1_input")

        self.label_3_input = QtWidgets.QLineEdit(MatplotlibWindow)
        self.label_3_input.setEnabled(True)
        self.label_3_input.setGeometry(QtCore.QRect(210, 580, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_3_input.setFont(font)
        self.label_3_input.setStyleSheet("background-color: rgb(58, 58, 58);\n"
                                         "color: rgb(57, 255, 87);\n"
                                         "selection-color: rgb(57, 255, 87);\n"
                                         "selection-background-color: rgb(58, 58, 58);")
        self.label_3_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3_input.setTabletTracking(False)
        self.label_3_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_3_input.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_3_input.setInputMask("")
        self.label_3_input.setText("")
        self.label_3_input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.label_3_input.setClearButtonEnabled(False)
        self.label_3_input.setFrame(False)
        validator = QtGui.QRegularExpressionValidator(self.label_3_input)
        validator.setRegularExpression(QtCore.QRegularExpression("^[А-я][а-я]{0,6}$}"))
        self.label_3_input.setValidator(validator)
        self.label_3_input.setMaxLength(4)
        self.label_3_input.setObjectName("label_3_input")

        self.label_3.hide()
        self.label_3_input.hide()

        self.retranslateUi(MatplotlibWindow)
        QtCore.QMetaObject.connectSlotsByName(MatplotlibWindow)

        self.add_functions()

    def retranslateUi(self, MatplotlibWindow):
        _translate = QtCore.QCoreApplication.translate
        MatplotlibWindow.setWindowTitle(_translate("MatplotlibWindow", "Графический калькулятор"))
        self.pushButton_go.setText(_translate("MatplotlibWindow", "GO"))
        self.pushButton_save.setText(_translate("MatplotlibWindow", "Сохранить png"))
        self.label_3.setText(_translate("MatplotlibWindow", "Единица измерения"))
        self.label_1.setText(_translate("MatplotlibWindow", "Высота"))
        self.label_2.setText(_translate("MatplotlibWindow", "Ширина"))
        self.label_3_input.setText(_translate("MatplotlibWindow", "см"))

    def add_functions(self):
        pass

